# Generated by Django 5.2.12 on 2026-03-17 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuteurEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_author', models.CharField(max_length=50)),
                ('birth_annee', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditeurData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_str', models.CharField(max_length=50)),
                ('societe_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse_loc', models.CharField(blank=True, max_length=50, null=True)),
                ('city_ville', models.CharField(blank=True, max_length=20, null=True)),
                ('state_prov', models.CharField(blank=True, max_length=10, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('tel_num', models.CharField(blank=True, max_length=15, null=True)),
                ('fax_num', models.CharField(blank=True, max_length=15, null=True)),
                ('infos_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivreItem',
            fields=[
                ('isbn_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title_nom', models.CharField(max_length=255)),
                ('pub_year', models.SmallIntegerField(blank=True, null=True)),
                ('desc_text', models.CharField(blank=True, max_length=50, null=True)),
                ('notes_str', models.CharField(blank=True, max_length=50, null=True)),
                ('sujet_topic', models.CharField(blank=True, max_length=50, null=True)),
                ('details_txt', models.TextField(blank=True, null=True)),
                ('is_dispo', models.BooleanField(default=True)),
                ('auteurs_rel', models.ManyToManyField(to='biblio_project.auteurentity')),
                ('editeur_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_project.editeurdata')),
            ],
        ),
        migrations.CreateModel(
            name='BookingResa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_project.livreitem')),
            ],
        ),
    ]
