# Generated by Django 5.2.12 on 2026-03-17 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('au_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=255)),
                ('year_born', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('pubid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('year_published', models.SmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_project.authors')),
                ('pub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_project.publishers')),
            ],
        ),
    ]
