# Generated by Django 5.2.9 on 2026-03-18 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_project', '0002_authors_publishers_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('annee_naissance', models.SmallIntegerField(blank=True, null=True, verbose_name='Année de naissance')),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
            },
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'éditeur")),
                ('societe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Raison sociale')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=15, null=True, verbose_name='Code Postal')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Éditeur',
                'verbose_name_plural': 'Éditeurs',
            },
        ),
        migrations.RemoveField(
            model_name='livreitem',
            name='auteurs_rel',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='bookingresa',
            name='book_cible',
        ),
        migrations.RemoveField(
            model_name='bookingresa',
            name='user_client',
        ),
        migrations.RemoveField(
            model_name='livreitem',
            name='editeur_link',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='pub_id',
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('annee_publication', models.SmallIntegerField(verbose_name='Année de publication')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('auteurs', models.ManyToManyField(to='biblio_project.auteur', verbose_name='Auteurs')),
                ('editeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_project.editeur', verbose_name='Éditeur')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('est_active', models.BooleanField(default=True, verbose_name='Réservation active')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio_project.livre', verbose_name='Livre réservé')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
            },
        ),
        migrations.DeleteModel(
            name='AuteurEntity',
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
        migrations.DeleteModel(
            name='BookingResa',
        ),
        migrations.DeleteModel(
            name='EditeurData',
        ),
        migrations.DeleteModel(
            name='LivreItem',
        ),
        migrations.DeleteModel(
            name='Publishers',
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
